// This file is generated by `flutterfire configure`.
// Replace with your generated file after creating a Firebase project.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS not supported');
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3jCWG2-kJpL5_Bnxt9Mc54ya6U4958I',
    appId: '1:55723804965:android:9164ffed0bb58e1fe2b2cc',
    messagingSenderId: '55723804965',
    projectId: 'lmsystemm',
    storageBucket: 'lmsystemm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZRSUgPDVdczRVQ40p4wOX9VL4Set2UmY',
    appId: '1:55723804965:ios:9b6ea72857a60386e2b2cc',
    messagingSenderId: '55723804965',
    projectId: 'lmsystemm',
    storageBucket: 'lmsystemm.firebasestorage.app',
    iosClientId: '55723804965-ha2d8ocfvjjluuknec78h6ko7qalc2pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sinkingFundApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf-zD5S7bAcaOAroIgcoLKBB3BMcCrU5Q',
    appId: '1:55723804965:web:3d694a841165a235e2b2cc',
    messagingSenderId: '55723804965',
    projectId: 'lmsystemm',
    authDomain: 'lmsystemm.firebaseapp.com',
    storageBucket: 'lmsystemm.firebasestorage.app',
  );

}